# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UEa6wN1ixKqzSy-JeNsyKLxKMdI0Co7e
"""

from setuptools import setup

setup(name='Fufi',
      version='0.0.1',
      url="https://github.com/Gaianeve/gym-Fufi",
      author="Gaia Bartoli",
      install_requires=["numpy >= 1.18.0", "gym>=0.2.3"]
)
